name: pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Job"
    runs-on: ubuntu-latest
    steps:
      - name: "ação um"
        run: echo "Hello World !!!"
      - name: "ação dois"
        run: | 
          cat ./text.txt
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
