name: pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  primeiro-job:
    name: "Job"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout do código"
        uses: actions/checkout@v4   # <-- baixa os arquivos do repositório
      - name: "ação dois"
        run: cat exemplo.txt   # agora funciona
  segundo-job:
    name: "Instalação do Ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
      - name: "Verificação da versão do NodeJS atual"
        run: node --version
